name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - test

jobs:
  gcc9:
    name: Build with gcc 9
    runs-on: ubuntu-22.04
    defaults: {}
      #continue-on-error: false
    steps:
    - name: Machine Information
      run: lscpu; free -h
    - name: System Information
      run: uname -a; uptime; cat /etc/lsb-release
    - name: Context Information
      run: id; pwd
    - name: Install Valgrind
      run: sudo apt-get update && sudo apt-get --no-install-recommends install valgrind
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make --version && make -j3 GCC=gcc-9 GXX=g++-9
      continue-on-error: false
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: gcc9
        path: build
