name: Test

on:
  workflow_dispatch:

jobs:
  test1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: uname
      run: uname -a
    - name: gcc
      run: gcc --version
    - name: gcc-12
      run: gcc-12 --version
    - name: make
      run: make --version
    - name: lscpu
      run: lscpu
    - name: id
      run: id
    - name: pwd
      run: pwd
    - name: ls
      run: ls -la
    - name: make
      run: make -B -j2 GCC=gcc-9 GXX=g++-9
    - name: make
      run: make -B -j3 GCC=gcc-9 GXX=g++-9
    - name: make
      run: make -B -j4 GCC=gcc-9 GXX=g++-9
