name: Test

on:
  workflow_dispatch:

jobs:
  test1:

    runs-on: ubuntu-latest

    steps:
    - name: uname
      run: uname -a
    - name: gcc
      run: gcc --version
    - name: make
      run: make --version
    - name: lscpu
      run: lscpu
    - name: id
      run: id
    - name: pwd
      run: pwd
    - name: ls
      run: ls -la
