name: Test

on: {workflow_dispatch:""}

jobs:
  test1:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get update && sudo apt-get install valgrind
    - name: checkout
      uses: actions/checkout@v4
    - name: uname
      run: uname -a
    - run: gcc --version
    - name: gcc-12
      run: gcc-12 --version
    - name: gcc-13
      run: gcc-13 --version
    - name: make
      run: make --version
    - name: valgrind
      run: valgrind --version
    - name: lscpu
      run: lscpu
    - name: free
      run: free -h
    - name: id
      run: id
    - name: pwd
      run: pwd
    - name: ls
      run: ls -la
    - name: make
      run: make -B -j3 GCC=gcc-9 GXX=g++-9
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build
  test2:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: make
      run: make -B -j3 GCC=gcc-9 GXX=g++-9
