name: Test

on:
  workflow_dispatch: {}
  push:
    branches:
    - test

jobs:
  gcc9:
    name: Build with gcc 9
    runs-on: ubuntu-22.04
    steps:
    - name: Machine Information
      run: lscpu; free -h; df -h .
    - name: System Information
      run: date; uname -a; uptime; cat /etc/lsb-release; ls /boot || true
    - name: Context Information
      run: id; pwd
    - name: Update Package DB
      run: sudo apt-get update
    - name: Install Valgrind
      run: sudo apt-get --no-install-recommends install valgrind
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make --version; gcc-9 --version; make -j3 GCC=gcc-9 GXX=g++-9
    - name: Check
      run: find build; cat mnl; cat test.mnl; make run
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: gcc9
        path: build
    - name: Run under valgrind
      run: valgrind --version; make run-valgrind
    - name: Performance Testing
      run: |
        TIMEFORMAT='Elapsed time: %Rs'
        for n in {1..5}; do
           sleep $((RANDOM * 10 / 32768))
           time ./mnl test.mnl &>/dev/null
        done
