name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - test

jobs:
  gcc9:
    name: Compile with gcc 9
    runs-on: ubuntu-22.04
    steps:
    - name: System Information
      run: lscpu; free -h; uname -a; cat /etc/lsb-release; uptime; id; pwd; gcc-9 --version; make --version
    - name: Install Valgrind
      run: sudo apt-get update && sudo apt-get install valgrind && valgrind --version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Make
      run: make -j3 GCC=gcc-9 GXX=g++-9
    - uses: actions/upload-artifact@v4
      with:
        name: gcc9
        path: build
